home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

larp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('ros/', include('ros.urls')),
]

ros/urls.py
from django.urls import path

from . import views

app_name = 'ros'
urlpatterns = [
    #path ('', views.MainView.as_view(), name='all'),
    path('creatures', views.CreatureListView.as_view(), name='creatures'),
    path('creatures/<int:pk>', views.CreatureDetailView.as_view(), name='creature_detail'),
    path('spells', views.SpellListView.as_view(), name='spells'),
    path('spells/<int:pk>', views.SpellDetailView.as_view(), name='spell_detail'),
    path('skills', views.SkillListView.as_view(), name='skills'),
    path('skills/<int:pk>', views.SkillDetailView.as_view(), name='skill_detail'),
    path('characters', views.CharacterListView.as_view(), name='characters'),
    path('characters/<int:pk>', views.CharacterDetailView.as_view(), name='character_detail'),
]

urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('ros/', include('ros.urls')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

ros/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Creature(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Creature must be greater than 1 character")]
    )
    details = models.TextField(default="")
    #moredetails = models.CharField()

    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Skill must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Spell(models.Model):
    name = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "spell must be greater than 1 character")]
    )
    #   level = models.IntegerField(default=1)

    def __str__(self):
        return self.name


class Character(models.Model):
    playerName = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Name must be greater than 1 character")]
    )
    CharacterName = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Name must be greater than 1 character")]
    )
    virtue = models.IntegerField(default=50)
    rep = models.IntegerField(default=50)
    xp = models.IntegerField(default=0)
    creatureType = models.ForeignKey(Creature, null=True, on_delete=models.SET_NULL)
    spells = models.ManyToManyField(Spell, through='CharacterSpell', verbose_name="list of spells")
    skills = models.ManyToManyField(Skill, through='CharacterSkill', verbose_name="list of skills")

    def __str__(self):
        return self.playerName


class CharacterSpell(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    spell = models.ForeignKey(Spell, on_delete=models.CASCADE)
    level = models.IntegerField(default=0)


class CharacterSkill(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    level = models.IntegerField(default=0)

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        print(request.get_host())
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)

ros/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from ros.models import Creature, Spell, Skill, Character, CharacterSpell
from ros.owner import OwnerListView, OwnerDetailView
#from autos.forms import MakeForm

# Create your views here.


class CreatureListView(OwnerListView):
    model = Creature


class SpellListView(OwnerListView):
    model = Spell
    skills = Skill.objects.all().values()   


class SkillListView(OwnerListView):
    model = Skill


class CharacterListView(OwnerListView):
    model = Character


class CreatureDetailView(OwnerDetailView):
    model = Creature
    template_name = "ros/creature_detail.html"
    def get(self, request, pk) :
        x = Creature.objects.get(id=pk)
        context = {'creature': x}
        return render(request, self.template_name, context)

class SpellDetailView(OwnerDetailView):
    model = Spell
    template_name = "ros/spell_detail.html"
    def get(self, request, pk) :
        x = Spell.objects.get(id=pk)
        context = {'spell': x}
        return render(request, self.template_name, context)

class SkillDetailView(OwnerDetailView):
    model = Skill
    template_name = "ros/skill_detail.html"
    def get(self, request, pk) :
        x = Skill.objects.get(id=pk)
        context = {'skill': x}
        return render(request, self.template_name, context)

class CharacterDetailView(OwnerDetailView):
    model = Character
    template_name = "ros/character_detail.html"
    def get(self, request, pk) :
        x = Character.objects.get(id=pk)
        y = CharacterSpell.objects.all()
        context = {'character': x,
                   'spells': y}
        return render(request, self.template_name, context)

home/templates/base_bootstrap.html
<!DOCTYPE html>
<html>
<head>
<!-- Edit dj4e-samples/settings.py and add APP_NAME = 'DJ4E Samples' or similar -->
<title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css"
    crossorigin="anonymous">

<link rel="stylesheet"
    href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css"
     crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    crossorigin="anonymous"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
    crossorigin="anonymous"></script>

<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

<meta name="dj4e-version" content="2022-11-01">

{% block head %} {% endblock %}

</head>
<body>
<div class="container">
{% block navbar %} {% endblock %}
{% block welcome %} {% endblock %}
{% block messages %}
    {% if messages %}
    {% for msg in messages %}
        <div class="alert alert-{{msg.level_tag}}" role="alert">
        {{msg.message}}
        </div>
    {% endfor %}
    {% endif %}
{% endblock %}
{% block content %}
{% endblock %}
</div>
{% block footer %} {% endblock %}
</body>
</html>

home/templates/home/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
  test
</p>
</body>
</html>

ros/templates/ros/character_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creature detail</title>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>{{character.CharacterName}}</h1>
</head>

<body>
<p>Player Name: {{character.playerName}}</p>
<p>Character Name: {{character.CharacterName}}</p>
<p>Experience: {{character.xp}}</p>
<p>Rep: {{character.rep}}</p>
<p>Virtue: {{character.virtue}}</p>
<p>Spells: </p>
<p>
<ul>
  {% for spell in spells %}
    <li>
        <a href="{% url 'ros:spell_detail' spell.id %}">{{ spell.spell }}</a>
    </li>
  {% endfor %}
</ul>
</p>
</body>
{% endblock %}
</html>

ros/templates/ros/character_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creatures</title>
</head>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Characters</h1>
<p>
{% if character_list %}
<ul>
  {% for character in character_list %}
    <li>
        <a href="{% url 'ros:character_detail' character.id %}">{{ character.CharacterName }}</a>

    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no creatures in the database.</p>
{% endif %}
</p>
{% endblock %}
</html>

ros/templates/ros/creature_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creature detail</title>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>{{creature.name}}</h1>
</head>

<body>
<p>
<p>creature: {{creature.name}}</p>
<p>Notes: {{creature.details}}</p>
</p>

</body>
{% endblock %}
</html>

ros/templates/ros/creature_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Creatures</title>
</head>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Creatures</h1>
<p>
{% if creature_list %}
<ul>
  {% for creature in creature_list %}
    <li>
        <a href="{% url 'ros:creature_detail' creature.id %}">{{ creature.name }}</a>

    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no creatures in the database.</p>
{% endif %}
</p>
{% endblock %}
</html>

ros/templates/ros/skill_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Skill detail</title>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>{{skill.name}}</h1>
</head>

<body>
<p>
<p>Skill: {{skill.name}}</p>
</p>

</body>
{% endblock %}
</html>

ros/templates/ros/skill_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Skills</title>
</head>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Skills</h1>
<p>
{% if skill_list %}
<ul>
  {% for skill in skill_list %}
    <li>
        <a href="{% url 'ros:skill_detail' skill.id %}">{{ skill.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no skills in the database.</p>
{% endif %}
</p>
{% endblock %}
</html>

ros/templates/ros/spell_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spell detail</title>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>{{spell.name}}</h1>
</head>

<body>
<p>
<p>Spell: {{spell.name}}</p>
</p>

</body>
{% endblock %}
</html>

ros/templates/ros/spell_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Spells</title>
</head>
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Spells</h1>
<p>
{% if spell_list %}
<ul>
  {% for spell in spell_list %}
    <li>
        <a href="{% url 'ros:spell_detail' spell.id %}">{{ spell.name }}</a>
    </li>
  {% endfor %}

</ul>
{% else %}
  <p>There are no spells in the database.</p>
{% endif %}
</p>
<p>
{% if skills %}
<ul>
  {% for skill in skills %}
    <li>
        <a href="{% url 'ros:skill_detail' skill.id %}">{{ skill.name }}</a>
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no skills in the database.</p>
{% endif %}
</p>
{% endblock %}
</html>